name: Go

on:
  push:
    branches: [ sudo-push-server ]
  pull_request:
    branches: [ sudo-push-server ]

jobs:

  build:
    runs-on: centos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
